language: android
jdk: oraclejdk8
sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
  
android:
  components:
    - tools
    - tools
    - platform-tools
    - android-22
    - build-tools-26.1.1
    - extra
    - sys-img-armeabi-v7a-android-22

script:
  - yes | sdkmanager "platforms;android-28" # accept license
  - chmod +x ./gradlew                        # make executable 
  - ./gradlew test jacocoTestReport
  - ./gradlew sonarqube -Dsonar.organization=carcassonne -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH

# benachrichtigungen per email ausschalten
notifications:
  email: 
    on_success: never # default: change
    on_failure: never # default: always